---
version: 1.2.2
slug: cups
name: CUPS Print Server
description: CUPS print server for network printing
url: https://github.com/arest/cups-addon
codenotary: andrea_restello@yahoo.it
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
homeassistant_api: true
host_network: true
map:
  - data:rw
  - share:rw
init: false
ports:
  631/tcp: 631
ports_description:
  631/tcp: CUPS web interface and printing port
options:
  admin_username: "admin"
  admin_password: "admin"
  power_on_before_print: false
  power_switch_entity_id: ""
  power_on_delay: 0
schema:
  admin_username: str
  admin_password: password
  power_on_before_print: bool
  power_switch_entity_id: "str?"
  power_on_delay: "int(0,60)"
startup: services
